<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ingresar</name>
   <tag></tag>
   <elementGuidId>a88e1dcf-8b51-4154-a7de-1aabe349e84d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-block.login-btn.mb-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Ingresar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e536ace8-f11c-4e25-9338-4d61eee2b0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>287d4529-f808-43f4-ab54-c82fdc6ae268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block login-btn mb-4</value>
      <webElementGuid>79325e36-8948-47b5-b600-114db188b9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>ee89ef6e-6b29-49b8-8ac9-8b87c197074f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-login[1]/html[1]/body[1]/main[@class=&quot;d-flex align-items-center min-vh-100 py-3 py-md-0&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;card login-card&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/a[@class=&quot;btn btn-block login-btn mb-4&quot;]</value>
      <webElementGuid>56c03863-7561-4880-bb0e-5492179eb809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ingresar')]</value>
      <webElementGuid>56c188f9-2c17-4029-8847-ce7ac0fc9362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>75ce8ba2-60b1-4cd7-8c68-5ecd7a60b9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correo'])[1]/following::a[1]</value>
      <webElementGuid>cbbd7988-ba5d-4596-9d50-bff67d91a9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ingresar']/parent::*</value>
      <webElementGuid>aa379734-64a8-4c77-89f5-f29b593f639f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>ffd52434-52a8-4ee6-a16d-9cc1ecdd6053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Ingresar' or . = 'Ingresar')]</value>
      <webElementGuid>bb26c2e1-48c1-4ddc-96a4-94bd1d93742a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
