<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ver</name>
   <tag></tag>
   <elementGuidId>78f7f3e6-767f-4efa-ab30-38917228431f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-outline-warning</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>742f3fae-26da-4c74-81df-463b29916285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0ea8e97-2c1f-4683-8754-087edaef9bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/administracion/alumnos</value>
      <webElementGuid>eea866a6-4b48-42f4-ae87-63a5a02c272c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-warning</value>
      <webElementGuid>a99e4343-2d5d-4c8d-83c3-51f111ab3494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d2102230-bf4c-49f3-a74b-75b4f629dc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ver</value>
      <webElementGuid>83eb1812-09e2-4961-a461-3f2fb6b6b280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-inicio-administracion[1]/html[1]/body[1]/div[@class=&quot;container centro&quot;]/div[@class=&quot;row justify-content-evenly&quot;]/div[@class=&quot;col-12 col-md-4 py-3&quot;]/div[@class=&quot;card text-center&quot;]/div[@class=&quot;card-img&quot;]/div[@class=&quot;overlay&quot;]/div[@class=&quot;overlay-content&quot;]/button[@class=&quot;btn btn-outline-warning&quot;]</value>
      <webElementGuid>4000fe2f-4c6a-4628-be1f-af13582a0e55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>08463308-6e30-4e8d-8ab2-375130ca464a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administración'])[1]/following::button[1]</value>
      <webElementGuid>c26e6dc5-070d-4542-b36b-d3182f265ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salir'])[1]/following::button[1]</value>
      <webElementGuid>88dc97c2-cd67-4b2a-a1de-2d94d0444732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumnos'])[1]/preceding::button[1]</value>
      <webElementGuid>ff65fa43-6423-4274-9f33-45e249e46a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver'])[2]/preceding::button[1]</value>
      <webElementGuid>4579d470-f731-40b1-8da4-debecfcdd0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ver']/parent::*</value>
      <webElementGuid>ffa45c5a-ccca-43e9-8905-038b3d38a970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>96e16218-a57f-4903-b57e-dae3c6e665fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Ver' or . = ' Ver')]</value>
      <webElementGuid>2a536aa3-650e-4fa1-b320-4befd826b194</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
