<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Fondos</name>
   <tag></tag>
   <elementGuidId>6cd2258b-0aa7-4aa0-9219-35ce658d0552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d9573956-2ee0-4571-bffc-d25096d63d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4133e1df-4ac7-4202-b6cc-09657fb0f49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>41bb1710-086c-413a-8a3d-c2e4400a0aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalAgregarFondos</value>
      <webElementGuid>93b8c239-78ad-4811-9d9f-e80dcc30ff5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary letras</value>
      <webElementGuid>fe2935a5-e967-47a6-8e37-b5f53667ce92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Fondos </value>
      <webElementGuid>f2510e24-ea2e-45af-a037-40168c84a07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/app-root[1]/app-administracion-alumnos[1]/html[1]/body[1]/div[@class=&quot;container centro&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-12 py-3&quot;]/table[@class=&quot;table table-primary table-striped&quot;]/tbody[1]/tr[6]/td[4]/button[@class=&quot;btn btn-primary letras&quot;]</value>
      <webElementGuid>f564a110-0aae-4d81-a1c0-7ab28f28d6c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>86cf68de-3372-47e3-8abe-52b552ee124b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Q0.00'])[1]/following::button[1]</value>
      <webElementGuid>d7b354d9-2993-4995-8c64-20043b6a0335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chocojay Morales'])[1]/following::button[1]</value>
      <webElementGuid>bd11721f-98e8-4326-afae-316d041d04cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dio'])[1]/preceding::button[1]</value>
      <webElementGuid>c5322abb-d0e4-4fd2-939b-adcb7253546d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brando'])[1]/preceding::button[1]</value>
      <webElementGuid>776dd7e6-61db-4c85-a6c7-c5d67d64e2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[4]/button</value>
      <webElementGuid>b087a0ec-b074-4fb1-a887-2ed8877f97b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Fondos ' or . = ' Fondos ')]</value>
      <webElementGuid>b5ae8d87-1ba8-4b6b-b13d-01fc81caa79f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
