<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Editar</name>
   <tag></tag>
   <elementGuidId>feaae1e5-7181-4ea4-bb10-d969f4536a7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a6915e3-c909-4fef-9c7b-62605bb4471f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e13a0d1-2c92-46c2-9cf9-7d2bae2a5506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>66c2aaf6-30f4-4470-931b-0e5d2d40ba51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalEditarProducto</value>
      <webElementGuid>7ba0da16-37b0-4863-9f0a-1652d9928835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>offcanvasExample</value>
      <webElementGuid>9355482c-5486-468a-83bf-db8e47d57282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary margin-left letras boton-mar</value>
      <webElementGuid>02071e93-f5d7-4098-bb41-d16b06f78da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Editar </value>
      <webElementGuid>330f7e05-4ff0-4886-a8a0-676f12756299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/app-root[1]/app-administracion-productos[1]/html[1]/body[1]/div[@class=&quot;container centro&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-4 py-3&quot;]/div[@class=&quot;card text-center&quot;]/div[@class=&quot;card-content&quot;]/button[@class=&quot;btn btn-primary margin-left letras boton-mar&quot;]</value>
      <webElementGuid>d8e74e00-c09b-4d2c-8d61-158fd04b05ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>9627b52d-a838-4d2e-87b6-25db59a1187d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choripan'])[1]/following::button[1]</value>
      <webElementGuid>50204396-54d5-4c0a-a439-9826292a74fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[4]/following::button[1]</value>
      <webElementGuid>b3542ee7-ecc5-4a05-8aa4-8d9055ae1e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[5]/preceding::button[1]</value>
      <webElementGuid>51136921-ed9f-4ace-b6a8-02327eb6b5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2022 Copyright: Grupo Kinal'])[1]/preceding::button[2]</value>
      <webElementGuid>8657960d-e5e7-4fa9-a2da-b6cd4da83a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/button</value>
      <webElementGuid>835b959b-2e50-44a2-ac94-7b4ee5cbf6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Editar ' or . = ' Editar ')]</value>
      <webElementGuid>79578713-2e49-4bba-b0c4-c0f7156c1a67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
