<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cantidad a agregar_cantidad</name>
   <tag></tag>
   <elementGuidId>78a89ac6-3cc8-44a9-a251-610a1fd9c150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputCantidad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputCantidad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfe09e96-6a69-4ecf-89bf-f72ac34e5e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0fa59af6-9731-4b81-9a60-0e4adcdf0270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>604d830d-4087-4970-845c-de96d4d3997e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCantidad</value>
      <webElementGuid>480ad26c-0ad5-4616-997b-cca676820445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cantidad</value>
      <webElementGuid>0a6cbf1a-532b-47ba-b5fa-6acbb614a14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>14161df2-8a16-4d59-90e8-3c7a323e157c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control letras ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>dd0b64ba-68b2-47ff-99fc-401137d9afde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCantidad&quot;)</value>
      <webElementGuid>86304ab0-a387-45a8-ae3f-c4f55837b78a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputCantidad']</value>
      <webElementGuid>33642f97-8439-4202-983c-5336374a9ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalAgregarFondos']/div/div/div[2]/form/div/input</value>
      <webElementGuid>235115e7-4784-4064-9fae-209c70d521ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>df67ea24-1dc5-4e9d-9569-d1a18dee53fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'inputCantidad' and @name = 'cantidad']</value>
      <webElementGuid>f3f8fef3-204f-4c03-be15-62a3e24ce5bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
