<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cantidad Producto_cantidad</name>
   <tag></tag>
   <elementGuidId>900a1017-9a46-46f3-8c93-8dc8d97aa241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputCantidadEditar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputCantidadEditar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8318669b-ee32-4ef4-aed6-2cb95e705e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5d5cea56-46f6-486a-b9e7-9b31ea7d7db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8b7211b6-e0cc-439d-86bd-b3f9897268ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ab680b7d-c2ff-42d7-826d-b5728aacc0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCantidadEditar</value>
      <webElementGuid>3388886a-ea90-4375-b781-6af7dba3abd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cantidad</value>
      <webElementGuid>24434d7d-16f4-49a3-bd17-1ed457b082ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>669d5b2b-5174-43a9-af05-265197ca92e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control letras ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>a8caebe4-df6c-4e24-a4f1-98ece6a70637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCantidadEditar&quot;)</value>
      <webElementGuid>d8bf3752-138b-4f60-b405-b5ed882d2c30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputCantidadEditar']</value>
      <webElementGuid>b6940091-67d1-4d5b-9734-9c5828c345f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditarProducto']/div/div/div[2]/form/div[4]/input</value>
      <webElementGuid>885c3f24-73ee-4e1b-8693-fc7ea2112197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>abd1b49f-1aaa-42c6-b013-ce291d8f1bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'inputCantidadEditar' and @name = 'cantidad']</value>
      <webElementGuid>1a41cf3a-94ab-4767-b548-c03733cade6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
