<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Precio Producto_precio</name>
   <tag></tag>
   <elementGuidId>b7144029-e411-4ac0-9afc-6bd0878d9142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputPrecio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputPrecio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca53f9a0-3920-4930-a21d-c0ec609c136c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>74dbe5fc-9e58-4c91-b48a-7a99f5f1bfd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f9d9a572-137b-4e29-bc0a-29a7a3626448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputPrecio</value>
      <webElementGuid>c2c6d27d-e63c-4a85-a28d-5eec3ede68d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>precio</value>
      <webElementGuid>e2be2757-0f00-4118-aab0-2f7b981c4cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8ea8fe40-6559-4f46-925c-98e986e8391b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control letras ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>ed785246-339b-4561-86f1-78b217f557e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalAgregarProducto&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content modal-contenido&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;inputPrecio&quot;]</value>
      <webElementGuid>435c1ce2-8209-4aab-aab7-e2aaaa5ff76d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputPrecio']</value>
      <webElementGuid>4af35f5e-3d0b-4f97-836f-cf02dd47fd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalAgregarProducto']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>566108be-c139-4386-8306-837b01f3527e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0e8a1490-2c65-4879-b18c-2ed94843ad0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'inputPrecio' and @name = 'precio']</value>
      <webElementGuid>462e41df-f1a9-4a95-a5b1-8f3d83d807f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
