<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ver</name>
   <tag></tag>
   <elementGuidId>980bc223-712e-442a-9c4d-78439bbe7ba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b482468-39f7-40e1-bf1e-074ad2fa4047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d95b823-19ab-4410-aa3a-c3041d95660a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/administracion/productos</value>
      <webElementGuid>a123c1dc-7ebb-4966-9065-bb5d7a169e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-warning</value>
      <webElementGuid>165af272-7336-4baa-be36-9ec0ba194fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0b4972f1-d21c-494b-aa97-16d56c42b870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ver</value>
      <webElementGuid>8f4bea6d-829f-4b5a-a8b6-c8833b220d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-inicio-administracion[1]/html[1]/body[1]/div[@class=&quot;container centro&quot;]/div[@class=&quot;row justify-content-evenly&quot;]/div[@class=&quot;col-12 col-md-4 py-3&quot;]/div[@class=&quot;card text-center&quot;]/div[@class=&quot;card-img&quot;]/div[@class=&quot;overlay&quot;]/div[@class=&quot;overlay-content&quot;]/button[@class=&quot;btn btn-outline-warning&quot;]</value>
      <webElementGuid>3254d91b-94e5-45aa-a1b1-baa75f2b73d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>9ebaa271-f4b0-4a72-a28b-2a34d959a37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumnos'])[1]/following::button[1]</value>
      <webElementGuid>b9f2b7b6-8bf9-4ec4-b871-1e7a09638884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver'])[1]/following::button[1]</value>
      <webElementGuid>849e9eba-230c-41c5-9f50-d456ad038108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Productos'])[1]/preceding::button[1]</value>
      <webElementGuid>09dc3e60-e9dd-407c-b1df-6f9f453559e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver'])[3]/preceding::button[1]</value>
      <webElementGuid>cb97dbf7-2191-4c22-828e-6bfdd5294456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>6bc5ca3a-8d4b-4756-a3b5-52bfa7468a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Ver' or . = ' Ver')]</value>
      <webElementGuid>4796e569-62be-4d3f-97f7-0723f073afc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
