<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Marbete</name>
   <tag></tag>
   <elementGuidId>b6535a67-88e7-4e87-bbb0-c45d5ff589b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>922f164e-9c0f-4a22-868a-33ec95ce7d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/usuario/marbete</value>
      <webElementGuid>1af1f664-a04c-458c-8b2a-e38e85d79512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active boton</value>
      <webElementGuid>badb8596-be47-484e-990b-6dd0f2f74c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/usuario/marbete</value>
      <webElementGuid>b085b03e-433c-4e78-a925-9c20a11e4f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Marbete</value>
      <webElementGuid>52d69ca5-f9c0-4cdb-ba23-f3d6aa81d0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/ul[@class=&quot;navbar-nav mx-auto mb-2 mb-lg-0 centrado&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link active boton&quot;]</value>
      <webElementGuid>ae4b2e88-2928-4972-8621-7b22ff043251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul/li[3]/a</value>
      <webElementGuid>2d881103-5538-40f0-bb36-14dfe0d59259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Marbete')]</value>
      <webElementGuid>a10056bc-09d7-4d83-aefb-dac9878a0353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cafetería'])[1]/following::a[1]</value>
      <webElementGuid>31b828f8-39ef-4a1c-b639-e6713fb9e656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administración'])[1]/following::a[2]</value>
      <webElementGuid>9ee22224-a03d-4fd5-b17f-f1ad7128c4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfil'])[1]/preceding::a[1]</value>
      <webElementGuid>1df3daa6-b804-4d7a-87f6-6158cc591803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cafetería'])[2]/preceding::a[1]</value>
      <webElementGuid>ecbd7f8e-479f-4bb8-8cff-65104995fe63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Marbete']/parent::*</value>
      <webElementGuid>43bcb4ca-8662-4839-ad81-e7ed08e2169a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/usuario/marbete')]</value>
      <webElementGuid>094b6714-0aba-40e3-95bd-22d4bfa5bca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>587d0b49-50f3-4e10-ab01-47b7325ea2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/usuario/marbete' and (text() = ' Marbete' or . = ' Marbete')]</value>
      <webElementGuid>86b12783-36dc-4533-b54c-67bb056cb5be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
