<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Perfil</name>
   <tag></tag>
   <elementGuidId>1a63552e-5560-47a6-9bf7-32e523111768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.d-flex.ng-untouched.ng-pristine.ng-valid > button.btn.btn-light.boton2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f34d5bc-a5ec-419a-82d0-33e2de284a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>70070d44-e938-4a4f-b20a-b4471834bf17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/usuario/perfil</value>
      <webElementGuid>62acd747-1ac0-4daf-bada-8b4adbacd769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light boton2</value>
      <webElementGuid>fc6b9ca2-4c40-4622-9abb-7bdd491a13a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>89c14f6d-1c1c-4419-8de7-086db1c7b73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Perfil</value>
      <webElementGuid>1a999e3a-3925-4fb9-ab65-b3d7654e262a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/form[@class=&quot;d-flex ng-untouched ng-pristine ng-valid&quot;]/button[@class=&quot;btn btn-light boton2&quot;]</value>
      <webElementGuid>448ad81e-2ab4-4e88-b35c-c86901d85ad6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>26c39766-79d3-4318-99e3-b952047f6117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/form/button</value>
      <webElementGuid>32bc9d31-4d18-473c-9d4c-028060d0c289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marbete'])[1]/following::button[1]</value>
      <webElementGuid>7df5ec1b-56ad-4086-ab9f-12303185b603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cafetería'])[1]/following::button[1]</value>
      <webElementGuid>aea88df6-7977-4e77-b1c1-971811cd7589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ochocojay-2017391'])[1]/preceding::button[1]</value>
      <webElementGuid>1fc12889-e8a6-448d-a75e-c72f549d2c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generar Marbete'])[1]/preceding::button[1]</value>
      <webElementGuid>0deb433b-8e1e-4367-884b-a4f3c5dce310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perfil']/parent::*</value>
      <webElementGuid>00ce419f-9f7b-46bc-a8f5-251e7e4e22a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>cb789627-88b3-45ba-abe3-d50e77c64eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Perfil' or . = ' Perfil')]</value>
      <webElementGuid>53fcd751-b983-44dd-af7c-461e6eac6d70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
