<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ver</name>
   <tag></tag>
   <elementGuidId>dbdbbd3a-2835-4163-bff7-fe2b6aa6dbc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-outline-warning</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0260a698-b811-45ed-848a-56a5fc157e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>271e9a2f-236c-4888-bd90-09f96e7aaf33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/usuario/administracion</value>
      <webElementGuid>f6b84493-4d68-473c-8a2a-f27fa431caa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-warning</value>
      <webElementGuid>6dac182c-70c0-4288-806b-18464f08d8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fd61131d-21e1-4c1a-9b81-1df7458aa96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ver</value>
      <webElementGuid>687d1b27-421a-4e67-ad61-46eecd50a0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-inicio-alumno[1]/html[1]/body[1]/div[@class=&quot;container centro&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-4 py-3&quot;]/div[@class=&quot;card text-center&quot;]/div[@class=&quot;card-img&quot;]/div[@class=&quot;overlay&quot;]/div[@class=&quot;overlay-content&quot;]/button[@class=&quot;btn btn-outline-warning&quot;]</value>
      <webElementGuid>61dfe282-708d-401e-84bf-4a359d34a9b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>bb60d0fd-98ff-4d17-aa21-7f576fc80c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicios'])[1]/following::button[1]</value>
      <webElementGuid>ad027898-5044-4c1d-a12a-44e72a002b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salir'])[1]/following::button[1]</value>
      <webElementGuid>d354cfff-c9ff-4794-b089-94486ce162ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administración'])[1]/preceding::button[1]</value>
      <webElementGuid>ae62a739-705a-4b84-8ea1-131851015045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver'])[2]/preceding::button[1]</value>
      <webElementGuid>66dd17ee-58da-4cae-a991-0539ce1b45c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ver']/parent::*</value>
      <webElementGuid>3c955db3-16dd-42aa-a65c-e7e930097291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>397da7f6-ce21-406d-b0fb-05190abfadd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Ver' or . = ' Ver')]</value>
      <webElementGuid>194b6c34-7ae6-43de-9216-ce01f05bf45a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
