<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cantidad_cantidad</name>
   <tag></tag>
   <elementGuidId>20b0f566-1a08-4319-812d-987fd4f70dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputCantidad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputCantidad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b0c7890-8f90-494b-8783-e2f46c2eb511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>59097e0b-98b7-4596-b0c1-5c073649487c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6947423b-000b-4677-bc41-f482c1f5c1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCantidad</value>
      <webElementGuid>6127e16a-e6f3-4547-8125-92641c83ce5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cantidad</value>
      <webElementGuid>5aa818ae-9082-49ee-ba9d-caa7dc5cd500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f03aee03-9119-4c2b-998e-e1aeb6c7288b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control letras ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>71d3947f-a2fc-42ab-8f8e-3a12f4ec1d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCantidad&quot;)</value>
      <webElementGuid>9a7b597e-fa1a-4549-a0d6-9c2c2ee26c44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputCantidad']</value>
      <webElementGuid>b2b07884-f28e-41fd-8c68-e3c63405b2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalCantidad']/div/div/div[2]/form/div/input</value>
      <webElementGuid>12ed0317-91d9-4201-a3aa-6cd4d2f8cccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c8d0844c-172c-4a22-be7f-d2c507cb210f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'inputCantidad' and @name = 'cantidad']</value>
      <webElementGuid>7b0f7ff8-15ee-498c-9ddb-9b375f5f63b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
