<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Correo_correo</name>
   <tag></tag>
   <elementGuidId>cd0f95cd-8d24-4bde-b511-62092c0479d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#correo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='correo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52cebd86-2b1b-4108-bbb4-b7bed4b24845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9deb2121-0e58-4e63-a2bc-7b04b7f3e38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>correo</value>
      <webElementGuid>c05abda7-b6e4-4133-9fc3-9ce263830c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>correo</value>
      <webElementGuid>eb9f7864-9daf-4f22-98b2-0918f8378f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Correo</value>
      <webElementGuid>04586c4d-c0a2-4c9e-aebf-1eb1a5ea9075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1a6d3d9d-f872-4ad2-b676-6f36e41f4eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>ee025c89-7ddf-4d4a-b495-f3b1b0f63fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;correo&quot;)</value>
      <webElementGuid>233775b2-beb5-4ac5-9646-c9318d687302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='correo']</value>
      <webElementGuid>3d078c64-ed4e-4e97-ab05-e3cdc08e5ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b1cb1707-dd3c-42c2-a523-735abddf440f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'correo' and @id = 'correo' and @placeholder = 'Correo']</value>
      <webElementGuid>f4cf580d-7244-40aa-95ce-553b962e939a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
