<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ingresar</name>
   <tag></tag>
   <elementGuidId>f1283a00-bfdd-46f0-8b8c-1825113dd86e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-block.login-btn.mb-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Ingresar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>58dc3591-7db3-46c1-b344-93773fd40ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>a5a3fef3-ec96-4f96-9813-b65760a30112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block login-btn mb-4</value>
      <webElementGuid>29ebf5c0-d672-46eb-9ca3-05916d8a0893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>5b47281b-03c6-4d5f-b9e7-d03354fe6f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-login[1]/html[1]/body[1]/main[@class=&quot;d-flex align-items-center min-vh-100 py-3 py-md-0&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;card login-card&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/a[@class=&quot;btn btn-block login-btn mb-4&quot;]</value>
      <webElementGuid>c8c4d72e-28db-4d94-bd07-0a7ebcdc3f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f3c0f123-88ee-43c3-9e6a-b4f16403a4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>51be8024-4f75-46f9-a2cd-e83ccabf84ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block login-btn mb-4</value>
      <webElementGuid>c9e2f10e-873e-4687-ab10-29c31ba74e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>2030b07b-6f25-4ae1-84d7-f294e1a76e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-login[1]/html[1]/body[1]/main[@class=&quot;d-flex align-items-center min-vh-100 py-3 py-md-0&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;card login-card&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/a[@class=&quot;btn btn-block login-btn mb-4&quot;]</value>
      <webElementGuid>c2cf1bc4-1361-4a08-ad74-8f8b86472604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25a2b6cc-b432-406f-869f-16961a2148af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>c438c4a0-13df-485e-991c-d3daf521dfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block login-btn mb-4</value>
      <webElementGuid>10611ebb-c5e9-4e8b-91fb-79b11b2823b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>8ff61756-d409-44dd-aaf1-813a378337b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-login[1]/html[1]/body[1]/main[@class=&quot;d-flex align-items-center min-vh-100 py-3 py-md-0&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;card login-card&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/a[@class=&quot;btn btn-block login-btn mb-4&quot;]</value>
      <webElementGuid>552be282-0382-4193-ae7d-395da558d1bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ingresar')]</value>
      <webElementGuid>242fb400-6192-4a91-af44-5431fe0298d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>a73acede-10bb-4e93-a0b0-d73b3dca3ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correo'])[1]/following::a[1]</value>
      <webElementGuid>b8cc2a21-b8ac-4084-b68e-775e5163717a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ingresar']/parent::*</value>
      <webElementGuid>9a3dd5e0-e9a2-4aa8-8dd4-e0a1048252c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>cfd419ac-1a88-4853-8fa8-5f8ecdb273ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Ingresar' or . = 'Ingresar')]</value>
      <webElementGuid>b57fa4e7-fddf-4eb1-b3cb-24d2ccdb5884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
