<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ver</name>
   <tag></tag>
   <elementGuidId>ecb88147-ec18-4211-a34b-ebb3add20e91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b06e83f1-b105-48a9-8a80-ae65476c51ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4c56c78d-1fce-4b2a-ae50-0b0470a61c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/administracion/productos</value>
      <webElementGuid>c528a90c-a011-4629-8d26-893077207b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-warning</value>
      <webElementGuid>a06a1f37-5195-48e4-9f42-852675df83bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>59b0f984-ad1a-45bc-897e-f97f0b39a469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ver</value>
      <webElementGuid>a2bc6ee5-4342-421c-96b9-2ff6e5ace49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-inicio-administracion[1]/html[1]/body[1]/div[@class=&quot;container centro&quot;]/div[@class=&quot;row justify-content-evenly&quot;]/div[@class=&quot;col-12 col-md-4 py-3&quot;]/div[@class=&quot;card text-center&quot;]/div[@class=&quot;card-img&quot;]/div[@class=&quot;overlay&quot;]/div[@class=&quot;overlay-content&quot;]/button[@class=&quot;btn btn-outline-warning&quot;]</value>
      <webElementGuid>73357750-d7e3-4c5a-a0d8-40f81a6331bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40464793-2bb7-4bfe-a086-c3a27562a643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eeff3d06-b823-484b-bd22-ea5e9e74ba8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/admin/usuarios</value>
      <webElementGuid>79078055-c2cd-4a50-82ab-56581ce621ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-warning</value>
      <webElementGuid>21fb54ea-f4c5-46e6-b8c1-2134f8884fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4871a422-92cb-4139-88af-5fc7e84ed21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ver</value>
      <webElementGuid>9fe6fd15-d8b4-4f1d-94dd-8519370ee8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-inicio-adminapp[1]/html[1]/body[1]/div[@class=&quot;container centro&quot;]/div[@class=&quot;row justify-content-evenly&quot;]/div[@class=&quot;col-12 col-md-4 py-3&quot;]/div[@class=&quot;card text-center&quot;]/div[@class=&quot;card-img&quot;]/div[@class=&quot;overlay&quot;]/div[@class=&quot;overlay-content&quot;]/button[@class=&quot;btn btn-outline-warning&quot;]</value>
      <webElementGuid>15479899-ed0a-4e65-8511-c904cbd27cef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>4d1651bd-e62a-457d-89c0-4f961352d608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumnos'])[1]/following::button[1]</value>
      <webElementGuid>ca7d357a-1d86-4e0a-a823-530583f52486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver'])[1]/following::button[1]</value>
      <webElementGuid>0b85c97e-e9be-4ec1-99d3-fc85b00ded21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Productos'])[1]/preceding::button[1]</value>
      <webElementGuid>0843e69a-6b05-441e-97fa-997f65106103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver'])[3]/preceding::button[1]</value>
      <webElementGuid>cad0e869-45ba-4ac5-9155-39b11c1faabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>dbb59906-3acb-436b-a612-a0a2f73c58c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Ver' or . = ' Ver')]</value>
      <webElementGuid>23456b40-07f7-4a26-ad6d-480d1a38f118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>f0b52ed9-dc37-43da-ba3c-bf1b408e0314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[1]/following::button[1]</value>
      <webElementGuid>14dd9dc1-9e74-4adc-918c-bb23e0432925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salir'])[1]/following::button[1]</value>
      <webElementGuid>1f718bba-9b39-417d-a7fd-c017982cb1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumnos'])[1]/preceding::button[1]</value>
      <webElementGuid>eddcec7c-3fbb-4eb6-89e7-7ba0447a3007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver'])[2]/preceding::button[1]</value>
      <webElementGuid>47bfae3f-71df-45c9-a9af-63fefb14999b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ver']/parent::*</value>
      <webElementGuid>ed127c4b-17ec-4dbd-80c6-df1cafc295e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>c8a94b5a-1df9-4afd-8643-51dfeaab2efa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
