<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apellidos_apellidos</name>
   <tag></tag>
   <elementGuidId>dab3f7f4-30aa-4697-add9-7018d0fe6064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputApellidos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputApellidos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00aac261-a149-4ceb-8d35-69f632767d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6350fdea-ae8c-45f6-9d90-5f2e5755bf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputApellidos</value>
      <webElementGuid>54bd0e49-f500-4f58-a40c-5f2658d76a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apellidos</value>
      <webElementGuid>c054877c-c517-4c5c-bb9d-afc445f4115c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a66fa6cb-10a0-48bc-98b1-e59d9715d277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control letras ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7b76c38b-ca41-4b8f-8f2c-314d2460bb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalAgregarUsuario&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content modal-contenido&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;inputApellidos&quot;]</value>
      <webElementGuid>5a007841-a9e4-4758-8ddf-f7f87f58e62d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputApellidos']</value>
      <webElementGuid>e11f4b3e-464a-4f74-8b43-1a86a1cfaca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalAgregarUsuario']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>bc110974-0a15-484a-a215-13abcd156844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>243d21a2-7155-4ad6-ba9a-bd3a017e9411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputApellidos' and @name = 'apellidos']</value>
      <webElementGuid>a0f39770-84ba-4615-9711-fe7d02e047e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
