<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cantidad Producto_cantidad</name>
   <tag></tag>
   <elementGuidId>f8970644-e363-4c9b-962d-968fb34b3fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputCantidad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputCantidad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e58c311-e927-4dcf-9a58-f42e100a5364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>23c09ee1-8eda-4041-82e6-270fdded1359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b57e339a-8005-4c82-9fdc-0569750b3e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>018359bc-c40d-4204-b246-a9a2b0db1e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCantidad</value>
      <webElementGuid>70aed992-fae2-4da9-8d67-260356ef2e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cantidad</value>
      <webElementGuid>5ba6547a-c726-470d-91b3-110edda90c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>00b11395-5c68-4877-ba99-7e40a84bbea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control letras ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>ad3208bc-c3ee-46a2-a59e-8b6578cfc682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCantidad&quot;)</value>
      <webElementGuid>754881aa-8c3c-4e26-bdf2-a2d1dee712bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputCantidad']</value>
      <webElementGuid>9a2114c4-25ce-4326-83f7-a02f65aa6a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalAgregarProducto']/div/div/div[2]/form/div[4]/input</value>
      <webElementGuid>1073f832-37b4-4c75-9e59-31dbd1468fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>224420b8-540a-4a60-bf63-18234a266ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'inputCantidad' and @name = 'cantidad']</value>
      <webElementGuid>74737291-895b-4515-83b5-b16651a6c429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
