<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero de Carnet_carnet</name>
   <tag></tag>
   <elementGuidId>58606b96-3afc-40ab-a2a1-5e250d0318ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputCarnet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputCarnet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ce90740-147b-4988-a042-6cccc25ffa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3f07cf2e-4748-43ba-aa0d-4305802c2f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a65a9a2f-a89a-4280-bee0-bbb61b4f250d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCarnet</value>
      <webElementGuid>3e11762c-164e-4165-8f5f-5b3a51aba1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carnet</value>
      <webElementGuid>ce34cd20-d64b-4d1c-9dd9-a58a3ab68adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>59413bc5-482a-471a-b17d-98e69ab8b607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control letras ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>73d190ab-b8bb-41ac-ae19-1631ee5e2488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalAgregarUsuario&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content modal-contenido&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;inputCarnet&quot;]</value>
      <webElementGuid>8242a312-a0f1-4513-bb35-3a5cbc567a83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputCarnet']</value>
      <webElementGuid>1e530823-3aab-4cc4-9e95-f47322ac7951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalAgregarUsuario']/div/div/div[2]/form/div[3]/input</value>
      <webElementGuid>90dc96ec-29d7-4f86-929e-1f306ac7fa97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>5c40a295-f45c-412c-aeb1-7f713b053cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'inputCarnet' and @name = 'carnet']</value>
      <webElementGuid>8fbdced5-d365-4036-b763-6e8c1afa91fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
