<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Precio Producto_precio</name>
   <tag></tag>
   <elementGuidId>2228beaa-a344-4e6c-a45d-24998be1d92c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputPrecio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputPrecio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6229aa4-e0ec-4fd6-8694-54dd614aff60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b320d028-3609-47f5-a179-2d0f2af6e18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0622a5be-1d1a-437b-a215-ca80bb1760bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputPrecio</value>
      <webElementGuid>6f8892f1-735b-4d08-9b7c-bbb446c06dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>precio</value>
      <webElementGuid>01739570-0b80-4e0d-8783-a005b51f328b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cab18a72-831d-4e98-8de7-b74778d24bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control letras ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>3a3243f8-de03-414a-a485-cf8c84b48874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalAgregarProducto&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content modal-contenido&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;inputPrecio&quot;]</value>
      <webElementGuid>20b13419-ca85-42b5-aa49-1007652cedf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputPrecio']</value>
      <webElementGuid>a64741ea-e8fd-42bd-be19-9aeddc5cef99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalAgregarProducto']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>6098fe45-1a54-436e-986f-5c9d4be318de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8a2c0e49-9cfd-4904-a05e-c2c9193b58fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'inputPrecio' and @name = 'precio']</value>
      <webElementGuid>4c3dbcc0-b624-44d4-a3ed-c60f069870f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
