<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombres_nombres</name>
   <tag></tag>
   <elementGuidId>7fe99671-58c1-4a00-9e5d-fd1049311c04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputNombres</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputNombres']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a5196d6-107e-473b-a239-fea09025ec9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79b36c8b-d9ea-444c-90ae-b12c53f1b463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputNombres</value>
      <webElementGuid>d97fef00-8b79-40b3-9e08-a3d20551b8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nombres</value>
      <webElementGuid>951402e7-36d2-4904-ac35-6a9efa08b0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>907375eb-ad1a-4580-b776-68e046bf6f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control letras ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>13a57167-92a6-4be5-8add-d3dc129eaa70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalAgregarUsuario&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content modal-contenido&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;inputNombres&quot;]</value>
      <webElementGuid>6047f760-2a26-4c00-8ff6-f35685f265de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputNombres']</value>
      <webElementGuid>952eeef1-ffef-4959-aa93-c8f7d67e14d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalAgregarUsuario']/div/div/div[2]/form/div/input</value>
      <webElementGuid>630f5bfe-a162-4a91-8a6b-0844b742602e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>50ef075f-1a85-47ab-a83e-3e1db7afa3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputNombres' and @name = 'nombres']</value>
      <webElementGuid>fd4a3bc0-bddb-413b-8e50-c25a5f419507</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
